### PR TITLE
Make FastFixtureTestCase work in Django 1.7.

### PR DESCRIPTION
**Pull request by Pike**
See also issue #193.

I wish I had an idea on how to write tests for this.

I didn't look into the transaction stuff in detail yet, and I'm not exactly sure if it's easy to resolve those in a backwards compatible manner.

### CODE REVIEW

**Comment by Pike** [comment]
Yay, random red.

https://travis-ci.org/django-nose/django-nose/builds/60888480 and https://travis-ci.org/django-nose/django-nose/builds/60884305 show a green for each test at least once.

**Comment by erikrose** [comment]
I consider this green. The reds are just ssl timeouts while downloading packages.

**Comment by jwhitlock** [comment]
@Pike - This happens a lot - TravisCI, PyPi have occasional bad network days.  When this happens, I re-run the failing build, rather than close/open.

When you click through to the failing build (https://travis-ci.org/django-nose/django-nose/jobs/60884311), do you see a grey reload button in the upper right corner?  This might only be available to project owners.

rebuild button

**Comment by Pike** [comment]
Only find the rerun button on my own projects, but not here, sadly.

**Comment by jwhitlock** [comment]
Thanks for doing my research :smile: I've hit the reload buttons, we'll get it green.  It's a busy weekend, so I'll have to look closer in a few days.

**Comment by jwhitlock** [comment]
Wow, that was one busy weekend.

@Pike - Could you rebase this onto the new master? I've made quite a few changes and it won't merge cleanly anymore.  ``git rebase -i master`` might do the trick.

I've also added some basic database tests in testapp/tests.py, but none using FastFixtureTestCase.  I'd appreciate some tests, which may just be a copy of the UsesFixtureTestCase.

**Comment by jwhitlock** [comment]
I'd like to see some tests for FastFixtureTestCase (issue #220) before I merge fixes.

**Comment by Pike** [comment]
I'm afraid I took this as far as I could. This works in django <= 1.7, but breaks because the enter_transaction_management (internal?) api was killed in 1.8 and above. How to write the code in a way that doesn't break is sadly beyond my understanding of that code :-(

**Pull request closed without merging**
